In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import datetime
from datetime import datetime as dt
import time

%matplotlib inline

In [2]:
# Read dataset into the notebook
df = pd.read_csv('siri.20121106.csv')

C:\Users\minogud2\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
print("Number of rows and columns: ", df.shape)

Number of rows and columns:  (1765912, 15)

In [4]:
df.head(1)

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Lon,Lat,Delay,BlockID,VehicleID,StopID,AtStop
0,1352160000000000,15,0,00150001,2012-11-05,5826,RD,0,-6.258584,53.340099,-361,15013,33210,4870,0

In [5]:
# alter format to readable datetime
df['Timestamp'] = pd.to_datetime(df['Timestamp'], format='%Y%m%d %H:%M:%S.%f')

In [6]:
df.head(50)

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Lon,Lat,Delay,BlockID,VehicleID,StopID,AtStop
0,1970-01-16 15:36:00.000,15,0,00150001,2012-11-05,5826,RD,0,-6.258584,53.340099,-361,15013,33210,4870,0
1,1970-01-16 15:36:00.000,46,0,046A1002,2012-11-05,7267,D2,0,-6.259093,53.345425,-1101,46004,36024,794,0
2,1970-01-16 15:36:00.000,14,0,00140001,2012-11-05,6206,D2,0,-6.257329,53.287521,-126,14003,33325,1047,0
3,1970-01-16 15:36:00.002,41,0,041B0002,2012-11-05,61,SL,0,-6.264167,53.453217,-623,41008,33631,3874,1
4,1970-01-16 15:36:00.002,63,0,null,2012-11-05,1116,D2,0,-6.171050,53.259201,292,63003,33137,3283,0
5,1970-01-16 15:36:00.002,39,0,039A1002,2012-11-05,3795,PO,0,-6.262447,53.346767,-532,39026,36060,1479,0
6,1970-01-16 15:36:00.002,65,0,00650001,2012-11-05,4004,RD,0,-6.594641,53.129776,-287,65003,38004,7283,0
7,1970-01-16 15:36:00.002,40,0,040D1001,2012-11-05,2466,HN,0,-6.258850,53.362499,-488,40207,33274,52,0
8,1970-01-16 15:36:00.002,4,0,null,2012-11-05,5076,HN,0,-6.261073,53.352112,0,4003,43035,4725,0
9,1970-01-16 15:36:00.002,11,0,00111002,2012-11-05,5241,D1,0,-6.230217,53.323002,-536,11001,33462,320,0
10,1970-01-16 15:36:00.002,31,0,00311001,2012-11-05,2819,CF,0,-6.241683,53.362484,-386,31006,33232,613,0
11,1970-01-16 15:36:00.002,27,0,00270001,2012-11-05,4976,RD,0,-6.290833,53.319332,0,27011,33415,2355,1
12,1970-01-16 15:36:00.002,67,0,00670001,2012-11-05,893,PO,0,-6.476370,53.355328,-160,67002,40002,3892,0
13,1970-01-16 15:36:00.002,79,0,00790001,2012-11-05,3533,CD,0,-6.332334,53.342850,328,79002,33411,2907,0
14,1970-01-16 15:36:00.002,32,0,null,2012-11-05,2757,CF,0,-6.246833,53.354599,775,32007,38083,3586,0
15,1970-01-16 15:36:00.002,42,0,00420002,2012-11-05,3880,CF,0,-6.174524,53.442135,0,42007,38021,3579,0
16,1970-01-16 15:36:00.002,66,0,066A0001,2012-11-05,2940,PO,0,-6.372633,53.355251,-362,66001,33588,3993,0
17,1970-01-16 15:36:00.002,79,0,00790001,2012-11-05,3511,CD,0,-6.296600,53.347717,29,79003,33191,2907,0
18,1970-01-16 15:36:00.002,140,0,null,2012-11-05,6225,HN,0,-6.268016,53.370628,0,140013,33505,274,0
19,1970-01-16 15:36:00.002,332,0,033B0001,2012-11-05,503,HN,0,-6.141323,53.490158,61,332001,33501,3722,0
20,1970-01-16 15:36:00.002,140,0,01400001,2012-11-05,6615,HN,0,-6.276083,53.343884,0,140010,33141,895,1
21,1970-01-16 15:36:00.002,26,0,null,2012-11-05,3013,PO,0,-6.465570,53.357151,0,66008,33584,5114,0
22,1970-01-16 15:36:00.002,44,0,00440001,2012-11-05,5009,D2,0,-6.220562,53.267975,500,44001,33259,3467,0
23,1970-01-16 15:36:00.002,37,0,null,2012-11-05,2098,PO,0,-6.272911,53.346794,0,37005,33586,7338,0
24,1970-01-16 15:36:00.002,83,0,083A0001,2012-11-05,7099,HN,0,-6.273733,53.419632,0,83002,40019,324,1
25,1970-01-16 15:36:00.002,272,0,027B1002,2012-11-05,374,HN,0,-6.243900,53.398499,169,272005,40013,324,0
26,1970-01-16 15:36:00.002,38,0,00381003,2012-11-05,1243,PO,0,-6.266693,53.356422,-50,38003,33556,818,0
27,1970-01-16 15:36:00.002,16,0,016C0001,2012-11-05,6175,SL,0,-6.254583,53.355534,-23,16017,33633,270,1
28,1970-01-16 15:36:00.002,31,0,null,2012-11-05,2916,CF,0,-6.191250,53.359051,0,31007,38088,296,0
29,1970-01-16 15:36:00.002,747,0,07470001,2012-11-05,4328,SL,0,-6.253083,53.371799,0,747005,40039,3665,1
30,1970-01-16 15:36:00.002,41,0,041C0001,2012-11-05,126,SL,0,-6.244452,53.450260,-464,41001,33626,3090,0
31,1970-01-16 15:36:00.002,39,0,00391001,2012-11-05,3622,PO,0,-6.333664,53.372768,-310,39003,33600,1847,0
32,1970-01-16 15:36:00.002,25,0,00250001,2012-11-05,713,CD,0,-6.349717,53.349232,-458,25014,33292,2220,0
33,1970-01-16 15:36:00.002,238,0,02390002,2012-11-05,1871,HN,0,-6.336783,53.395100,-218,238002,40033,4411,0
34,1970-01-16 15:36:00.002,43,0,00431001,2012-11-05,3954,CF,0,-6.235034,53.358368,-23,43003,38082,296,1
35,1970-01-16 15:36:00.002,140,0,01401001,2012-11-05,6612,HN,0,-6.277017,53.416817,259,140007,33450,7149,1
36,1970-01-16 15:36:00.004,46,0,046A1001,2012-11-05,7417,D2,0,-6.242417,53.326218,-413,46018,36019,804,0
37,1970-01-16 15:36:00.004,38,0,00700001,2012-11-05,1390,PO,0,-6.475322,53.419350,-579,38014,33581,3332,0
38,1970-01-16 15:36:00.004,13,0,00131012,2012-11-05,4106,HN,0,-6.278217,53.416733,-263,13107,40029,281,1
39,1970-01-16 15:36:00.004,NaN,0,null,2012-11-05,2741,CF,0,-6.165066,53.394527,0,29005,33035,730,0
40,1970-01-16 15:36:00.004,150,0,01500001,2012-11-05,1547,RD,0,-6.278584,53.325851,-260,150011,33252,1099,0
41,1970-01-16 15:36:00.004,145,0,01450001,2012-11-05,6691,D1,0,-6.123250,53.192467,-763,145012,38033,2962,0
42,1970-01-16 15:36:00.004,27,0,077A1001,2012-11-05,4993,CD,0,-6.261395,53.344349,-248,27023,33521,1358,0
43,1970-01-16 15:36:00.004,15,0,00151001,2012-11-05,5929,HN,0,-6.162066,53.402668,401,15105,33502,6317,1
44,1970-01-16 15:36:00.004,NaN,0,null,2012-11-05,318,HN,0,-6.278217,53.418182,179,272006,43048,296,0
45,1970-01-16 15:36:00.004,145,0,01841001,2012-11-05,1212,D1,0,-6.111500,53.206467,2076,145011,33647,4657,1
46,1970-01-16 15:36:00.004,83,0,083A0001,2012-11-05,7174,HN,0,-6.313667,53.403633,0,83010,40032,2492,1
47,1970-01-16 15:36:00.004,38,0,00380001,2012-11-05,1269,PO,0,-6.379093,53.392433,404,38010,33563,1814,0
48,1970-01-16 15:36:00.004,84,0,00840001,2012-11-05,6010,D1,1,-6.101119,53.204365,-776,84005,33464,4156,0
49,1970-01-16 15:36:00.004,14,0,00611001,2012-11-05,5676,D1,0,-6.231000,53.317383,0,14001,33640,341,1

In [7]:
group = df.groupby(['JourneyPatternID'])

test_group = group.get_group(('046A1002'))

#Check how many there are
test_group

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Lon,Lat,Delay,BlockID,VehicleID,StopID,AtStop
1,1970-01-16 15:36:00.000,46,0,046A1002,2012-11-05,7267,D2,0,-6.259093,53.345425,-1101,46004,36024,794,0
316,1970-01-16 15:36:00.039,46,0,046A1002,2012-11-05,7267,D2,0,-6.255533,53.346035,-1043,46004,36024,320,1
489,1970-01-16 15:36:00.059,46,0,046A1002,2012-11-05,7267,D2,0,-6.255517,53.346035,-1043,46004,36024,320,1
632,1970-01-16 15:36:00.079,46,0,046A1002,2012-11-05,7267,D2,0,-6.252850,53.345901,-1043,46004,36024,320,1
788,1970-01-16 15:36:00.098,46,0,046A1002,2012-11-05,7267,D2,0,-6.252850,53.345901,-983,46004,36024,320,1
812,1970-01-16 15:36:00.100,46,0,046A1002,2012-11-05,7267,D2,0,-6.249000,53.345531,-983,46004,36024,320,1
959,1970-01-16 15:36:00.120,46,0,046A1002,2012-11-05,7267,D2,0,-6.248767,53.344833,-983,46004,36024,320,1
1088,1970-01-16 15:36:00.138,46,0,046A1002,2012-11-05,7267,D2,0,-6.249100,53.344265,-983,46004,36024,320,1
1239,1970-01-16 15:36:00.158,46,0,046A1002,2012-11-05,7267,D2,0,-6.249383,53.343884,-922,46004,36024,320,1
1387,1970-01-16 15:36:00.179,46,0,046A1002,2012-11-05,7267,D2,0,-6.250417,53.342167,-922,46004,36024,320,1
1515,1970-01-16 15:36:00.199,46,0,046A1002,2012-11-05,7267,D2,0,-6.250317,53.341450,-922,46004,36024,320,1
1664,1970-01-16 15:36:00.217,46,0,046A1002,2012-11-05,7267,D2,0,-6.250317,53.341450,-863,46004,36024,320,1
1689,1970-01-16 15:36:00.219,46,0,046A1002,2012-11-05,7267,D2,0,-6.250417,53.341366,-863,46004,36024,320,1
1818,1970-01-16 15:36:00.240,46,0,046A1002,2012-11-05,7267,D2,0,-6.249784,53.340851,-863,46004,36024,320,1
1976,1970-01-16 15:36:00.262,46,0,046A1002,2012-11-05,7267,D2,0,-6.247083,53.339901,-863,46004,36024,320,1
2091,1970-01-16 15:36:00.278,46,0,046A1002,2012-11-05,7267,D2,0,-6.247083,53.339901,-802,46004,36024,320,1
2119,1970-01-16 15:36:00.280,46,0,046A1002,2012-11-05,7267,D2,0,-6.246067,53.339535,-802,46004,36024,320,1
2237,1970-01-16 15:36:00.298,46,0,046A1002,2012-11-05,7267,D2,0,-6.242533,53.338348,-802,46004,36024,320,1
2356,1970-01-16 15:36:00.319,46,0,046A1002,2012-11-05,7267,D2,0,-6.239833,53.337284,-802,46004,36024,320,1
2492,1970-01-16 15:36:00.339,46,0,046A1002,2012-11-05,7267,D2,0,-6.238234,53.336266,-742,46004,36024,320,1
2618,1970-01-16 15:36:00.359,46,0,046A1002,2012-11-05,7267,D2,0,-6.238150,53.336216,-742,46004,36024,320,1
2734,1970-01-16 15:36:00.381,46,0,046A1002,2012-11-05,7267,D2,0,-6.237583,53.335518,-742,46004,36024,320,1
2844,1970-01-16 15:36:00.398,46,0,046A1002,2012-11-05,7267,D2,0,-6.237583,53.335518,-682,46004,36024,320,1
2875,1970-01-16 15:36:00.400,46,0,046A1002,2012-11-05,7267,D2,0,-6.235800,53.332966,-682,46004,36024,320,1
2982,1970-01-16 15:36:00.420,46,0,046A1002,2012-11-05,7267,D2,0,-6.233167,53.330448,-682,46004,36024,320,1
3081,1970-01-16 15:36:00.440,46,0,046A1002,2012-11-05,7267,D2,0,-6.232666,53.330017,-682,46004,36024,320,1
3179,1970-01-16 15:36:00.458,46,0,046A1002,2012-11-05,7267,D2,0,-6.231333,53.329266,-622,46004,36024,320,1
3315,1970-01-16 15:36:00.481,46,0,046A1002,2012-11-05,7267,D2,0,-6.230633,53.328949,-622,46004,36024,320,1
3404,1970-01-16 15:36:00.501,46,0,046A1002,2012-11-05,7267,D2,0,-6.230633,53.328949,-622,46004,36024,320,1
3524,1970-01-16 15:36:00.519,46,0,046A1002,2012-11-05,7267,D2,0,-6.230617,53.328949,-622,46004,36024,320,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1763811,1970-01-16 15:37:26.128,46,0,046A1002,2012-11-06,7267,D2,0,-6.254848,53.334019,-603,46004,36003,909,0
1763879,1970-01-16 15:37:26.143,46,0,046A1002,2012-11-06,7405,D1,0,-6.241683,53.338051,-181,46017,33398,320,1
1763959,1970-01-16 15:37:26.149,46,0,046A1002,2012-11-06,7267,D2,0,-6.256655,53.335735,-640,46004,36003,786,0
1764009,1970-01-16 15:37:26.159,46,0,046A1002,2012-11-06,7405,D1,0,-6.241683,53.338051,-121,46017,33398,320,1
1764046,1970-01-16 15:37:26.163,46,0,046A1002,2012-11-06,7405,D1,0,-6.240150,53.337502,-121,46017,33398,320,1
1764154,1970-01-16 15:37:26.171,46,0,046A1002,2012-11-06,7267,D2,0,-6.256472,53.337212,-691,46004,36003,786,0
1764206,1970-01-16 15:37:26.183,46,0,046A1002,2012-11-06,7405,D1,0,-6.237633,53.335632,-121,46017,33398,320,1
1764298,1970-01-16 15:37:26.189,46,0,046A1002,2012-11-06,7267,D2,0,-6.256155,53.338757,-747,46004,36003,786,0
1764358,1970-01-16 15:37:26.203,46,0,046A1002,2012-11-06,7405,D1,0,-6.235767,53.332951,-121,46017,33398,320,1
1764451,1970-01-16 15:37:26.210,46,0,046A1002,2012-11-06,7267,D2,0,-6.257496,53.339115,-764,46004,36003,786,0
1764498,1970-01-16 15:37:26.220,46,0,046A1002,2012-11-06,7405,D1,0,-6.235767,53.332951,-61,46017,33398,320,1
1764541,1970-01-16 15:37:26.224,46,0,046A1002,2012-11-06,7405,D1,0,-6.233300,53.330502,-61,46017,33398,320,1
1764641,1970-01-16 15:37:26.232,46,0,046A1002,2012-11-06,7267,D2,0,-6.258530,53.340221,-811,46004,36003,790,0
1764688,1970-01-16 15:37:26.242,46,0,046A1002,2012-11-06,7405,D1,0,-6.231333,53.329250,-61,46017,33398,320,1
1764789,1970-01-16 15:37:26.250,46,0,046A1002,2012-11-06,7267,D2,0,-6.258266,53.341103,-830,46004,36003,790,0
1764825,1970-01-16 15:37:26.262,46,0,046A1002,2012-11-06,7405,D1,0,-6.231000,53.329117,-61,46017,33398,320,1
1764939,1970-01-16 15:37:26.270,46,0,046A1002,2012-11-06,7267,D2,0,-6.258003,53.342064,-851,46004,36003,790,0
1764999,1970-01-16 15:37:26.280,46,0,046A1002,2012-11-06,7405,D1,0,-6.231000,53.329117,-1,46017,33398,320,1
1765043,1970-01-16 15:37:26.284,46,0,046A1002,2012-11-06,7405,D1,0,-6.231017,53.329132,-1,46017,33398,320,1
1765169,1970-01-16 15:37:26.303,46,0,046A1002,2012-11-06,7405,D1,0,-6.230683,53.328983,-1,46017,33398,320,1
1765275,1970-01-16 15:37:26.311,46,0,046A1002,2012-11-06,7267,D2,0,-6.260260,53.343544,-977,46004,36003,792,0
1765315,1970-01-16 15:37:26.323,46,0,046A1002,2012-11-06,7405,D1,0,-6.230683,53.328999,-1,46017,33398,320,1
1765396,1970-01-16 15:37:26.329,46,0,046A1002,2012-11-06,7267,D2,0,-6.260834,53.343842,-977,46004,36003,794,0
1765469,1970-01-16 15:37:26.339,46,0,046A1002,2012-11-06,7405,D1,0,-6.230683,53.328999,0,46017,33398,320,1
1765509,1970-01-16 15:37:26.343,46,0,046A1002,2012-11-06,7405,D1,0,-6.230683,53.328999,0,46017,33398,320,1
1765594,1970-01-16 15:37:26.349,46,0,046A1002,2012-11-06,7267,D2,0,-6.260852,53.343876,-977,46004,36003,794,0
1765651,1970-01-16 15:37:26.361,46,0,046A1002,2012-11-06,7405,D1,0,-6.230683,53.328999,0,46017,33398,320,1
1765741,1970-01-16 15:37:26.370,46,0,046A1002,2012-11-06,7267,D2,0,-6.260872,53.344128,-977,46004,36003,794,0
1765780,1970-01-16 15:37:26.382,46,0,046A1002,2012-11-06,7405,D1,0,-6.230567,53.328918,0,46017,33398,320,1
1765861,1970-01-16 15:37:26.390,46,0,046A1002,2012-11-06,7267,D2,0,-6.259929,53.344521,-1004,46004,36003,794,0

In [8]:
# Save cleaned dataframe to new CSV file
test_group.to_csv('46a.csv', index=False)

In [9]:
test_group.head(5)

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Lon,Lat,Delay,BlockID,VehicleID,StopID,AtStop
1,1970-01-16 15:36:00.000,46,0,046A1002,2012-11-05,7267,D2,0,-6.259093,53.345425,-1101,46004,36024,794,0
316,1970-01-16 15:36:00.039,46,0,046A1002,2012-11-05,7267,D2,0,-6.255533,53.346035,-1043,46004,36024,320,1
489,1970-01-16 15:36:00.059,46,0,046A1002,2012-11-05,7267,D2,0,-6.255517,53.346035,-1043,46004,36024,320,1
632,1970-01-16 15:36:00.079,46,0,046A1002,2012-11-05,7267,D2,0,-6.252850,53.345901,-1043,46004,36024,320,1
788,1970-01-16 15:36:00.098,46,0,046A1002,2012-11-05,7267,D2,0,-6.252850,53.345901,-983,46004,36024,320,1

In [10]:
# Read dataset into the notebook
df2 = pd.read_csv("stops.txt", header='infer', sep=",")

In [11]:
df2.head(5)

       ﻿stop_id       stop_name   stop_lat  stop_lon
0  8220DB000002  Parnell Square  53.352244 -6.263693
1  8220DB000003  Parnell Square  53.352308 -6.263781
2  8220DB000004  Parnell Square  53.352565 -6.264161
3  8220DB000006  Parnell Square  53.352740 -6.264439
4  8220DB000007  Parnell Square  53.352832 -6.264556

In [12]:
# Read dataset into the notebook
df3 = pd.read_csv("stop_times.txt", header='infer', sep=",")

In [13]:
df3.head(5)

,﻿trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,1.1598.0-33A-b12-1.451.I,16:15:00,16:15:00,8240DB003813,1,Swords,0,0,0.000000
1,1.1598.0-33A-b12-1.451.I,16:15:39,16:15:39,8240DB003814,2,Swords,0,0,827.070328
2,1.1598.0-33A-b12-1.451.I,16:17:11,16:17:11,8240DB003815,3,Swords,0,0,2746.649492
3,1.1598.0-33A-b12-1.451.I,16:17:22,16:17:22,8240DB003816,4,Swords,0,0,2973.900755
4,1.1598.0-33A-b12-1.451.I,16:17:44,16:17:44,8240DB003566,5,Swords,0,0,3447.155571

In [63]:
df3['is46A'] = df3['﻿trip_id'].str.contains('46A', na=False)

# test_group3 = group3.str.contains('12564.3514.0-46A-b12-1', na=False)

In [64]:
df3.head(5)

,﻿trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,is46A
0,1.1598.0-33A-b12-1.451.I,16:15:00,16:15:00,8240DB003813,1,Swords,0,0,0.000000,False
1,1.1598.0-33A-b12-1.451.I,16:15:39,16:15:39,8240DB003814,2,Swords,0,0,827.070328,False
2,1.1598.0-33A-b12-1.451.I,16:17:11,16:17:11,8240DB003815,3,Swords,0,0,2746.649492,False
3,1.1598.0-33A-b12-1.451.I,16:17:22,16:17:22,8240DB003816,4,Swords,0,0,2973.900755,False
4,1.1598.0-33A-b12-1.451.I,16:17:44,16:17:44,8240DB003566,5,Swords,0,0,3447.155571,False

In [65]:
group3 = df3.groupby(['is46A'])

test_group3 = group3.get_group((True))

In [66]:
test_group3

,﻿trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,is46A
170829,12564.3514.0-46A-b12-1.308.O,07:00:00,07:00:00,8220DB000807,1,Dun Laoghaire,0,0,0.000000,True
170830,12564.3514.0-46A-b12-1.308.O,07:01:03,07:01:03,8220DB000808,2,Dun Laoghaire,0,0,343.962310,True
170831,12564.3514.0-46A-b12-1.308.O,07:01:36,07:01:36,8220DB000809,3,Dun Laoghaire,0,0,535.012042,True
170832,12564.3514.0-46A-b12-1.308.O,07:02:28,07:02:28,8220DB000810,4,Dun Laoghaire,0,0,841.908087,True
170833,12564.3514.0-46A-b12-1.308.O,07:03:00,07:03:00,8220DB000811,5,Dun Laoghaire,0,0,1032.448991,True
170834,12564.3514.0-46A-b12-1.308.O,07:03:28,07:03:28,8220DB000812,6,Dun Laoghaire,0,0,1248.784379,True
170835,12564.3514.0-46A-b12-1.308.O,07:04:00,07:04:00,8220DB000813,7,Dun Laoghaire,0,0,1488.514043,True
170836,12564.3514.0-46A-b12-1.308.O,07:05:00,07:05:00,8220DB000814,8,Dun Laoghaire,0,0,1845.838825,True
170837,12564.3514.0-46A-b12-1.308.O,07:06:14,07:06:14,8220DB000081,9,Dun Laoghaire,0,0,2126.912833,True
170838,12564.3514.0-46A-b12-1.308.O,07:07:24,07:07:24,8220DB000817,10,Dun Laoghaire,0,0,2387.820194,True
170839,12564.3514.0-46A-b12-1.308.O,07:08:00,07:08:00,8220DB000818,11,Dun Laoghaire,0,0,2528.413339,True
170840,12564.3514.0-46A-b12-1.308.O,07:09:00,07:09:00,8220DB000819,12,Dun Laoghaire,0,0,2881.466483,True
170841,12564.3514.0-46A-b12-1.308.O,07:11:01,07:11:01,8220DB000264,13,Dun Laoghaire,0,0,3282.287390,True
170842,12564.3514.0-46A-b12-1.308.O,07:13:00,07:13:00,8220DB006059,14,Dun Laoghaire,0,0,3677.705633,True
170843,12564.3514.0-46A-b12-1.308.O,07:14:46,07:14:46,8220DB000334,15,Dun Laoghaire,0,0,4112.825418,True
170844,12564.3514.0-46A-b12-1.308.O,07:17:28,07:17:28,8220DB000406,16,Dun Laoghaire,0,0,4780.816465,True
170845,12564.3514.0-46A-b12-1.308.O,07:19:00,07:19:00,8220DB000747,17,Dun Laoghaire,0,0,5159.594456,True
170846,12564.3514.0-46A-b12-1.308.O,07:20:03,07:20:03,8220DB000842,18,Dun Laoghaire,0,0,5468.132848,True
170847,12564.3514.0-46A-b12-1.308.O,07:21:00,07:21:00,8220DB000845,19,Dun Laoghaire,0,0,5754.685614,True
170848,12564.3514.0-46A-b12-1.308.O,07:22:03,07:22:03,8220DB000846,20,Dun Laoghaire,0,0,6019.379259,True
170849,12564.3514.0-46A-b12-1.308.O,07:23:00,07:23:00,8220DB000847,21,Dun Laoghaire,0,0,6261.816249,True
170850,12564.3514.0-46A-b12-1.308.O,07:24:09,07:24:09,8220DB000848,22,Dun Laoghaire,0,0,6572.306317,True
170851,12564.3514.0-46A-b12-1.308.O,07:25:00,07:25:00,8220DB002795,23,Dun Laoghaire,0,0,6804.844563,True
170852,12564.3514.0-46A-b12-1.308.O,07:26:01,07:26:01,8220DB000756,24,Dun Laoghaire,0,0,7145.883208,True
170853,12564.3514.0-46A-b12-1.308.O,07:27:00,07:27:00,8220DB000757,25,Dun Laoghaire,0,0,7470.850898,True
170854,12564.3514.0-46A-b12-1.308.O,07:28:00,07:28:00,8220DB000758,26,Dun Laoghaire,0,0,7673.315674,True
170855,12564.3514.0-46A-b12-1.308.O,07:29:09,07:29:09,8220DB000759,27,Dun Laoghaire,0,0,8069.944330,True
170856,12564.3514.0-46A-b12-1.308.O,07:30:00,07:30:00,8220DB000760,28,Dun Laoghaire,0,0,8363.371420,True
170857,12564.3514.0-46A-b12-1.308.O,07:30:32,07:30:32,8220DB000761,29,Dun Laoghaire,0,0,8685.194353,True
170858,12564.3514.0-46A-b12-1.308.O,07:31:00,07:31:00,8220DB000762,30,Dun Laoghaire,0,0,8963.652321,True
...,...,...,...,...,...,...,...,...,...,...
741651,6806.3449.0-46A-b12-1.298.I,08:23:00,08:23:00,8250DB002065,6,Mountjoy Sq,0,0,1844.442389,True
741652,6806.3449.0-46A-b12-1.298.I,08:25:35,08:25:35,8250DB004727,7,Mountjoy Sq,0,0,2530.667633,True
741653,6806.3449.0-46A-b12-1.298.I,08:27:17,08:27:17,8250DB004728,8,Mountjoy Sq,0,0,2982.663901,True
741654,6806.3449.0-46A-b12-1.298.I,08:28:00,08:28:00,8250DB000461,9,Mountjoy Sq,0,0,3173.033569,True
741655,6806.3449.0-46A-b12-1.298.I,08:29:00,08:29:00,8250DB002068,10,Mountjoy Sq,0,0,3414.460577,True
741656,6806.3449.0-46A-b12-1.298.I,08:30:00,08:30:00,8250DB002069,11,Mountjoy Sq,0,0,3759.711436,True
741657,6806.3449.0-46A-b12-1.298.I,08:32:00,08:32:00,8250DB002070,12,Mountjoy Sq,0,0,4146.481582,True
741658,6806.3449.0-46A-b12-1.298.I,08:33:49,08:33:49,8250DB002084,13,Mountjoy Sq,0,0,4518.946345,True
741659,6806.3449.0-46A-b12-1.298.I,08:37:00,08:37:00,8250DB000768,14,Mountjoy Sq,0,0,5171.267064,True
741660,6806.3449.0-46A-b12-1.298.I,08:39:00,08:39:00,8220DB000769,15,Mountjoy Sq,0,0,5490.694347,True
741661,6806.3449.0-46A-b12-1.298.I,08:40:19,08:40:19,8220DB000770,16,Mountjoy Sq,0,0,5936.357894,True
741662,6806.3449.0-46A-b12-1.298.I,08:40:53,08:40:53,8220DB000771,17,Mountjoy Sq,0,0,6126.748020,True
741663,6806.3449.0-46A-b12-1.298.I,08:42:00,08:42:00,8220DB000772,18,Mountjoy Sq,0,0,6502.406227,True
741664,6806.3449.0-46A-b12-1.298.I,08:43:03,08:43:03,8220DB000773,19,Mountjoy Sq,0,0,6704.704407,True
741665,6806.3449.0-46A-b12-1.298.I,08:44:18,08:44:18,8220DB000774,20,Mountjoy Sq,0,0,6947.034760,True
741666,6806.3449.0-46A-b12-1.298.I,08:46:00,08:46:00,8220DB000775,21,Mountjoy Sq,0,0,7271.596285,True
741667,6806.3449.0-46A-b12-1.298.I,08:48:00,08:48:00,8220DB000776,22,Mountjoy Sq,0,0,7554.979157,True
741668,6806.3449.0-46A-b12-1.298.I,08:49:08,08:49:08,8220DB000777,23,Mountjoy Sq,0,0,7763.707803,True
741669,6806.3449.0-46A-b12-1.298.I,08:51:00,08:51:00,8220DB000906,24,Mountjoy Sq,0,0,8105.130503,True
741670,6806.3449.0-46A-b12-1.298.I,08:52:14,08:52:14,8220DB000907,25,Mountjoy Sq,0,0,8340.466698,True
741671,6806.3449.0-46A-b12-1.298.I,08:53:14,08:53:14,8220DB000908,26,Mountjoy Sq,0,0,8532.446877,True
741672,6806.3449.0-46A-b12-1.298.I,08:54:34,08:54:34,8220DB000909,27,Mountjoy Sq,0,0,8786.272179,True
741673,6806.3449.0-46A-b12-1.298.I,08:56:00,08:56:00,8220DB000786,28,Mountjoy Sq,0,0,9048.761259,True
741674,6806.3449.0-46A-b12-1.298.I,08:58:58,08:58:58,8220DB000790,29,Mountjoy Sq,0,0,9608.387674,True
741675,6806.3449.0-46A-b12-1.298.I,09:01:00,09:01:00,8220DB000792,30,Mountjoy Sq,0,0,9991.686262,True
741676,6806.3449.0-46A-b12-1.298.I,09:02:56,09:02:56,8220DB000794,31,Mountjoy Sq,0,0,10269.447120,True
741677,6806.3449.0-46A-b12-1.298.I,09:05:10,09:05:10,8220DB000320,32,Mountjoy Sq,0,0,10591.691002,True
741678,6806.3449.0-46A-b12-1.298.I,09:09:00,09:09:00,8220DB000274,33,Mountjoy Sq,0,0,11140.522150,True
741679,6806.3449.0-46A-b12-1.298.I,09:10:22,09:10:22,8220DB000002,34,Mountjoy Sq,0,0,11559.350178,True
741680,6806.3449.0-46A-b12-1.298.I,09:13:00,09:13:00,8220DB004962,35,Mountjoy Sq,0,0,12373.206182,True

In [67]:
# Save cleaned dataframe to new CSV file
test_group3.to_csv('46a_stoptimes.csv', index=False)

In [68]:
# Read dataset into the notebook
df46A = pd.read_csv('46a.csv')

In [69]:
# Read dataset into the notebook
df46AStops = pd.read_csv('46a_stoptimes.csv')

In [70]:
df46A.head(5)

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Lon,Lat,Delay,BlockID,VehicleID,StopID,AtStop
0,1970-01-16 15:36:00.000,46,0,046A1002,2012-11-05,7267,D2,0,-6.259093,53.345425,-1101,46004,36024,794,0
1,1970-01-16 15:36:00.039,46,0,046A1002,2012-11-05,7267,D2,0,-6.255533,53.346035,-1043,46004,36024,320,1
2,1970-01-16 15:36:00.059,46,0,046A1002,2012-11-05,7267,D2,0,-6.255517,53.346035,-1043,46004,36024,320,1
3,1970-01-16 15:36:00.079,46,0,046A1002,2012-11-05,7267,D2,0,-6.252850,53.345901,-1043,46004,36024,320,1
4,1970-01-16 15:36:00.098,46,0,046A1002,2012-11-05,7267,D2,0,-6.252850,53.345901,-983,46004,36024,320,1

In [73]:
df46AStops.head(5)

,?trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,is46A
0,12564.3514.0-46A-b12-1.308.O,07:00:00,07:00:00,8220DB000807,1,Dun Laoghaire,0,0,0.000000,True
1,12564.3514.0-46A-b12-1.308.O,07:01:03,07:01:03,8220DB000808,2,Dun Laoghaire,0,0,343.962310,True
2,12564.3514.0-46A-b12-1.308.O,07:01:36,07:01:36,8220DB000809,3,Dun Laoghaire,0,0,535.012042,True
3,12564.3514.0-46A-b12-1.308.O,07:02:28,07:02:28,8220DB000810,4,Dun Laoghaire,0,0,841.908087,True
4,12564.3514.0-46A-b12-1.308.O,07:03:00,07:03:00,8220DB000811,5,Dun Laoghaire,0,0,1032.448991,True